In [1]:
import torch
import torch.nn.functional as F
tensor = torch.tensor([[1,2,3],[4,5,6]])
print("original tensor:")
print(tensor)
target_shape = (3, 3)
current_shape = tensor.shape
pad_left = 0
pad_right = 0
pad_top = 0
pad_bottom = 0
if current_shape[0] < target_shape[0]:
    pad_bottom = target_shape[0] - current_shape[0]
if current_shape[1] < target_shape[1]:
    pad_right = target_shape[1] - current_shape[1]
padded_tensor = F.pad(tensor,(pad_left, pad_right, pad_top, pad_bottom),mode='constant',value=0)
print("\npadded tensor:")
print(padded_tensor)


original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

padded tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [0, 0, 0]])


In [3]:
import tensorflow as tf
x=tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [6]:
x=tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [13]:
x = tf.random.normal(shape=(2, 1),mean=0.,stddev=1.)
print(x)

tf.Tensor(
[[-0.29098752]
 [ 0.29441333]], shape=(2, 1), dtype=float32)


In [15]:
x = tf.random.uniform(shape=(3,1),minval=0.,maxval=1.)
print(x)

tf.Tensor(
[[0.5929041]
 [0.3978455]
 [0.470994 ]], shape=(3, 1), dtype=float32)


In [19]:
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0.

In [20]:
#tensor is not assinable
x = tf.ones(shape=(2, 2))
x[0, 0]=0.

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [21]:
v=tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.18022095],
       [ 0.543374  ],
       [-0.6058236 ]], dtype=float32)>


In [23]:
v.assign(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [24]:
v[0, 0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [25]:
v.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

In [27]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
